
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:43:57 IST (Sep 10 2019 07:13:57 UTC)

// Verification Directory fv/eight_code 

module two_code_3(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (v), .Y (b));
endmodule

module two_code(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (v), .Y (b));
endmodule

module two_code_1(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (v), .Y (b));
endmodule

module two_code_2(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (v), .Y (b));
endmodule

module four_code(v, s1, s2, a, b, c, d);
  input v, s1, s2;
  output a, b, c, d;
  wire v, s1, s2;
  wire a, b, c, d;
  wire a1, a2;
  two_code g1(v, s2, a1, a2);
  two_code_1 g2(a1, s1, a, b);
  two_code_2 g3(a2, s1, c, d);
endmodule

module two_code_4(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (v), .Y (b));
endmodule

module two_code_5(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (v), .Y (b));
endmodule

module two_code_6(v, s, a, b);
  input v, s;
  output a, b;
  wire v, s;
  wire a, b;
  NOR2BXL g17(.AN (v), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (v), .Y (b));
endmodule

module four_code_1(v, s1, s2, a, b, c, d);
  input v, s1, s2;
  output a, b, c, d;
  wire v, s1, s2;
  wire a, b, c, d;
  wire a1, a2;
  two_code_4 g1(.v (v), .s (s2), .a (a1), .b (a2));
  two_code_5 g2(.v (a1), .s (s1), .a (a), .b (b));
  two_code_6 g3(.v (a2), .s (s1), .a (c), .b (d));
endmodule

module eight_code(v, s1, s2, s3, a1, a2, a3, a4, a5, a6, a7, a8);
  input v, s1, s2, s3;
  output a1, a2, a3, a4, a5, a6, a7, a8;
  wire v, s1, s2, s3;
  wire a1, a2, a3, a4, a5, a6, a7, a8;
  wire b1, b2;
  two_code_3 g1(v, s3, b1, b2);
  four_code g2(b1, s1, s2, a1, a2, a3, a4);
  four_code_1 g3(b2, s1, s2, a5, a6, a7, a8);
endmodule

