
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 20:49:00 IST (Sep  4 2019 15:19:00 UTC)

// Verification Directory fv/q1_a 

module q1_a(a, b, c, d, o_p);
  input a, b, c, d;
  output o_p;
  wire a, b, c, d;
  wire o_p;
  AO22X1 g20(.A0 (d), .A1 (c), .B0 (b), .B1 (a), .Y (o_p));
endmodule

