
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 16:01:14 IST (Oct 22 2019 10:31:14 UTC)

// Verification Directory fv/serial_multiplier 

module four_lac(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_10;
  wire n_11;
  AO22X1 g250(.A0 (n_2), .A1 (n_11), .B0 (a[3]), .B1 (b[3]), .Y (c1));
  MXI2XL g251(.A (n_10), .B (n_11), .S0 (n_2), .Y (s[3]));
  CLKINVX1 g252(.A (n_10), .Y (n_11));
  AOI22X1 g253(.A0 (n_1), .A1 (n_8), .B0 (a[2]), .B1 (b[2]), .Y (n_10));
  MXI2XL g254(.A (n_7), .B (n_8), .S0 (n_1), .Y (s[2]));
  CLKINVX1 g255(.A (n_7), .Y (n_8));
  AOI22X1 g256(.A0 (n_5), .A1 (n_4), .B0 (a[1]), .B1 (b[1]), .Y (n_7));
  MXI2XL g257(.A (n_0), .B (n_5), .S0 (n_4), .Y (s[1]));
  CLKINVX1 g258(.A (n_0), .Y (n_5));
  XOR2X1 g259(.A (b[0]), .B (a[0]), .Y (s[0]));
  XOR2X1 g260(.A (b[1]), .B (a[1]), .Y (n_4));
  XOR2X1 g261(.A (b[3]), .B (a[3]), .Y (n_2));
  XOR2X1 g262(.A (b[2]), .B (a[2]), .Y (n_1));
  NAND2XL g263(.A (a[0]), .B (b[0]), .Y (n_0));
endmodule

module serial_multiplier(clk, rst, a, b, P);
  input clk, rst;
  input [3:0] a, b;
  output [7:0] P;
  wire clk, rst;
  wire [3:0] a, b;
  wire [7:0] P;
  wire [7:0] z;
  wire [4:0] sum;
  wire [3:0] x;
  wire [2:0] i;
  wire UNCONNECTED_HIER_Z, n_0, n_1, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13, n_16, n_30, n_31;
  wire n_32, n_33, n_40;
  four_lac g1({n_30, n_31, n_32, n_33}, z[7:4], UNCONNECTED_HIER_Z,
       sum[3:0], sum[4]);
  CLKINVX2 g190(.A (rst), .Y (n_16));
  AND2X1 g214(.A (b[3]), .B (x[0]), .Y (n_30));
  AND2X1 g215(.A (b[2]), .B (x[0]), .Y (n_31));
  AND2X1 g216(.A (b[0]), .B (x[0]), .Y (n_33));
  AND2X1 g217(.A (b[1]), .B (x[0]), .Y (n_32));
  SDFFQXL \P_reg[7] (.CK (clk), .D (P[7]), .SI (z[7]), .SE (n_13), .Q
       (P[7]));
  SDFFQXL \P_reg[1] (.CK (clk), .D (P[1]), .SI (z[1]), .SE (n_13), .Q
       (P[1]));
  SDFFQXL \P_reg[2] (.CK (clk), .D (P[2]), .SI (z[2]), .SE (n_13), .Q
       (P[2]));
  SDFFQXL \P_reg[0] (.CK (clk), .D (P[0]), .SI (z[0]), .SE (n_13), .Q
       (P[0]));
  SDFFRHQX1 \i_reg[1] (.RN (n_16), .CK (clk), .D (n_0), .SI (i[1]), .SE
       (i[2]), .Q (i[1]));
  SDFFQXL \P_reg[4] (.CK (clk), .D (P[4]), .SI (z[4]), .SE (n_13), .Q
       (P[4]));
  SDFFQXL \P_reg[3] (.CK (clk), .D (P[3]), .SI (z[3]), .SE (n_13), .Q
       (P[3]));
  SDFFQXL \P_reg[6] (.CK (clk), .D (P[6]), .SI (z[6]), .SE (n_13), .Q
       (P[6]));
  SDFFQXL \P_reg[5] (.CK (clk), .D (P[5]), .SI (z[5]), .SE (n_13), .Q
       (P[5]));
  SDFFSRHQX1 \x_reg[1] (.RN (n_10), .SN (n_8), .CK (clk), .D (x[2]),
       .SI (x[1]), .SE (i[2]), .Q (x[1]));
  SDFFSRHQX1 \x_reg[2] (.RN (n_5), .SN (n_6), .CK (clk), .D (x[3]), .SI
       (x[2]), .SE (i[2]), .Q (x[2]));
  SDFFSRHQX1 \x_reg[3] (.RN (n_3), .SN (n_7), .CK (clk), .D (x[0]), .SI
       (x[3]), .SE (i[2]), .Q (x[3]));
  SDFFRHQX1 \z_reg[6] (.RN (n_16), .CK (clk), .D (sum[3]), .SI (z[6]),
       .SE (i[2]), .Q (z[6]));
  SDFFRHQX1 \z_reg[4] (.RN (n_16), .CK (clk), .D (sum[1]), .SI (z[4]),
       .SE (i[2]), .Q (z[4]));
  SDFFSRHQX1 \x_reg[0] (.RN (n_9), .SN (n_4), .CK (clk), .D (x[1]), .SI
       (x[0]), .SE (i[2]), .Q (x[0]));
  SDFFRHQX1 \i_reg[0] (.RN (n_16), .CK (clk), .D (n_1), .SI (i[2]), .SE
       (i[0]), .Q (i[0]));
  SDFFRHQX1 \z_reg[0] (.RN (n_16), .CK (clk), .D (z[1]), .SI (z[0]),
       .SE (i[2]), .Q (z[0]));
  SDFFRHQX1 \z_reg[5] (.RN (n_16), .CK (clk), .D (sum[2]), .SI (z[5]),
       .SE (i[2]), .Q (z[5]));
  SDFFRHQX1 \z_reg[1] (.RN (n_16), .CK (clk), .D (z[2]), .SI (z[1]),
       .SE (i[2]), .Q (z[1]));
  SDFFRHQX1 \z_reg[2] (.RN (n_16), .CK (clk), .D (z[3]), .SI (z[2]),
       .SE (i[2]), .Q (z[2]));
  SDFFRHQX1 \z_reg[3] (.RN (n_16), .CK (clk), .D (sum[0]), .SI (z[3]),
       .SE (i[2]), .Q (z[3]));
  SDFFRHQX1 \z_reg[7] (.RN (n_16), .CK (clk), .D (sum[4]), .SI (z[7]),
       .SE (i[2]), .Q (z[7]));
  AND2X8 g1039(.A (n_12), .B (n_16), .Y (n_13));
  NOR3X1 g1040(.A (i[1]), .B (i[0]), .C (n_1), .Y (n_12));
  OR2X1 g1042(.A (a[1]), .B (n_16), .Y (n_10));
  OR2X1 g1043(.A (a[0]), .B (n_16), .Y (n_9));
  NAND2XL g1044(.A (a[1]), .B (rst), .Y (n_8));
  NAND2XL g1046(.A (a[3]), .B (rst), .Y (n_7));
  NAND2XL g1047(.A (a[2]), .B (rst), .Y (n_6));
  OR2X1 g1048(.A (a[2]), .B (n_16), .Y (n_5));
  NAND2XL g1049(.A (a[0]), .B (rst), .Y (n_4));
  OR2X1 g1050(.A (a[3]), .B (n_16), .Y (n_3));
  XOR2XL g2(.A (i[0]), .B (i[1]), .Y (n_0));
  DFFRX1 \i_reg[2] (.RN (n_16), .CK (clk), .D (n_40), .Q (i[2]), .QN
       (n_1));
  OAI2BB1X1 g1060(.A0N (i[1]), .A1N (i[0]), .B0 (n_1), .Y (n_40));
endmodule

