
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct  4 2019 00:26:38 IST (Oct  3 2019 18:56:38 UTC)

// Verification Directory fv/wallace 

module half(a, b, s, c);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g17(.A (a), .B (b), .CO (c), .S (s));
endmodule

module full(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (a), .CI (b), .CO (c1), .S (s));
endmodule

module full_1(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (a), .CI (b), .CO (c1), .S (s));
endmodule

module half_1(a, b, s, c);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g17(.A (a), .B (b), .CO (c), .S (s));
endmodule

module half_2(a, b, s, c);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g17(.A (a), .B (b), .CO (c), .S (s));
endmodule

module full_2(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (a), .CI (b), .CO (c1), .S (s));
endmodule

module full_3(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module full_4(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module half_3(a, b, s, c);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g17(.A (a), .B (b), .CO (c), .S (s));
endmodule

module full_5(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module full_6(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module full_7(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module wallace(x, y, z);
  input [3:0] x, y;
  output [7:0] z;
  wire [3:0] x, y;
  wire [7:0] z;
  wire [3:0] p0;
  wire [3:0] p1;
  wire [3:0] p2;
  wire [11:0] s;
  wire [11:0] c;
  wire [3:0] p3;
  wire \c[0]_1 ;
  half g1(p0[1], p1[0], z[1], \c[0]_1 );
  full g2(p0[2], p1[1], p2[0], s[1], c[1]);
  full_1 g3(p0[3], p1[2], p2[1], s[2], c[2]);
  half_1 g4(p2[2], p1[3], s[3], c[3]);
  half_2 g5(\c[0]_1 , s[1], z[2], c[4]);
  full_2 g6(c[1], s[2], p3[0], s[5], c[5]);
  full_3 g7(c[2], p3[1], s[3], s[6], c[6]);
  full_4 g8(c[3], p3[2], p2[3], s[7], c[7]);
  half_3 g9(c[4], s[5], z[3], c[8]);
  full_5 g10(c[8], c[5], s[6], z[4], c[9]);
  full_6 g11(c[9], c[6], s[7], z[5], c[10]);
  full_7 g12(c[10], p3[3], c[7], z[6], z[7]);
  AND2X1 g129(.A (y[2]), .B (x[1]), .Y (p2[1]));
  AND2X1 g130(.A (y[0]), .B (x[1]), .Y (p0[1]));
  AND2X1 g131(.A (y[0]), .B (x[3]), .Y (p0[3]));
  AND2X1 g132(.A (y[3]), .B (x[2]), .Y (p3[2]));
  AND2XL g133(.A (y[0]), .B (x[0]), .Y (z[0]));
  AND2X1 g134(.A (y[2]), .B (x[2]), .Y (p2[2]));
  AND2X1 g135(.A (y[2]), .B (x[3]), .Y (p2[3]));
  AND2X1 g136(.A (y[1]), .B (x[0]), .Y (p1[0]));
  AND2X1 g137(.A (y[1]), .B (x[1]), .Y (p1[1]));
  AND2X1 g138(.A (y[3]), .B (x[1]), .Y (p3[1]));
  AND2X1 g139(.A (y[0]), .B (x[2]), .Y (p0[2]));
  AND2X1 g140(.A (y[2]), .B (x[0]), .Y (p2[0]));
  AND2X1 g141(.A (y[3]), .B (x[0]), .Y (p3[0]));
  AND2X1 g142(.A (y[3]), .B (x[3]), .Y (p3[3]));
  AND2X1 g143(.A (y[1]), .B (x[2]), .Y (p1[2]));
  AND2X1 g144(.A (y[1]), .B (x[3]), .Y (p1[3]));
endmodule

