
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 04:07:37 IST (Sep  4 2019 22:37:37 UTC)

// Verification Directory fv/NOR 

module NOR(a, b, c);
  input a, b;
  output c;
  wire a, b;
  wire c;
  NOR2XL g10(.A (b), .B (a), .Y (c));
endmodule


