
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  9 2019 00:29:37 IST (Sep  8 2019 18:59:37 UTC)

// Verification Directory fv/eight_de 

module two_de_3(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de_1(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de_2(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (i_p), .Y (b));
endmodule

module four_de(i_p, a, b, c, d, s1, s2);
  input i_p, s1, s2;
  output a, b, c, d;
  wire i_p, s1, s2;
  wire a, b, c, d;
  wire a1, a2;
  two_de_1 g1(a1, a, b, s1);
  two_de_2 g2(a2, c, d, s1);
  two_de gg(i_p, a1, a2, s2);
endmodule

module two_de_5(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de_6(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de_4(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (i_p), .Y (b));
endmodule

module four_de_1(i_p, a, b, c, d, s1, s2);
  input i_p, s1, s2;
  output a, b, c, d;
  wire i_p, s1, s2;
  wire a, b, c, d;
  wire a1, a2;
  two_de_5 g1(.i_p (a1), .a (a), .b (b), .s (s1));
  two_de_6 g2(.i_p (a2), .a (c), .b (d), .s (s1));
  two_de_4 gg(.i_p (i_p), .a (a1), .b (a2), .s (s2));
endmodule

module eight_de(i_p, a1, a2, a3, a4, a5, a6, a7, a8, s1, s2, s3);
  input i_p, s1, s2, s3;
  output a1, a2, a3, a4, a5, a6, a7, a8;
  wire i_p, s1, s2, s3;
  wire a1, a2, a3, a4, a5, a6, a7, a8;
  wire b1, b2;
  two_de_3 g1(i_p, b1, b2, s3);
  four_de g2(b1, a1, a2, a3, a4, s1, s2);
  four_de_1 g3(b2, a5, a6, a7, a8, s1, s2);
endmodule

