
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 20:50:59 IST (Sep  4 2019 15:20:59 UTC)

// Verification Directory fv/q1_b 

module q1_b(a, b, c, d, e, f, o_p);
  input a, b, c, d, e, f;
  output o_p;
  wire a, b, c, d, e, f;
  wire o_p;
  wire n_0;
  NOR2BXL g48(.AN (f), .B (n_0), .Y (o_p));
  AOI32XL g49(.A0 (c), .A1 (b), .A2 (a), .B0 (d), .B1 (e), .Y (n_0));
endmodule

