
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 04:32:20 IST (Sep  4 2019 23:02:20 UTC)

// Verification Directory fv/XOR 

module XOR(a, b, c);
  input a, b;
  output c;
  wire a, b;
  wire c;
  CLKXOR2X1 g10(.A (b), .B (a), .Y (c));
endmodule


