
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 17:51:14 IST (Sep 26 2019 12:21:14 UTC)

// Verification Directory fv/sixteen_lac 

module four_lac(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_9;
  OAI21XL g352(.A0 (n_9), .A1 (n_3), .B0 (n_0), .Y (c1));
  MXI2XL g353(.A (n_2), .B (n_3), .S0 (n_9), .Y (s[3]));
  AOI22XL g354(.A0 (n_7), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_9));
  CLKXOR2X1 g355(.A (n_1), .B (n_7), .Y (s[2]));
  ADDFX1 g356(.A (b[1]), .B (a[1]), .CI (n_4), .CO (n_7), .S (s[1]));
  ADDFX1 g357(.A (b[0]), .B (a[0]), .CI (ci), .CO (n_4), .S (s[0]));
  CLKINVX1 g358(.A (n_2), .Y (n_3));
  CLKXOR2X1 g359(.A (b[3]), .B (a[3]), .Y (n_2));
  CLKXOR2X1 g360(.A (b[2]), .B (a[2]), .Y (n_1));
  NAND2XL g361(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module four_lac_1(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_9;
  OAI21XL g352(.A0 (n_9), .A1 (n_3), .B0 (n_0), .Y (c1));
  MXI2XL g353(.A (n_2), .B (n_3), .S0 (n_9), .Y (s[3]));
  AOI22XL g354(.A0 (n_7), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_9));
  CLKXOR2X1 g355(.A (n_1), .B (n_7), .Y (s[2]));
  ADDFX1 g356(.A (b[1]), .B (a[1]), .CI (n_4), .CO (n_7), .S (s[1]));
  ADDFX1 g357(.A (b[0]), .B (a[0]), .CI (ci), .CO (n_4), .S (s[0]));
  CLKINVX1 g358(.A (n_2), .Y (n_3));
  CLKXOR2X1 g359(.A (b[3]), .B (a[3]), .Y (n_2));
  CLKXOR2X1 g360(.A (b[2]), .B (a[2]), .Y (n_1));
  NAND2XL g361(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module four_lac_2(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_9;
  OAI21XL g352(.A0 (n_9), .A1 (n_3), .B0 (n_0), .Y (c1));
  MXI2XL g353(.A (n_2), .B (n_3), .S0 (n_9), .Y (s[3]));
  AOI22XL g354(.A0 (n_7), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_9));
  CLKXOR2X1 g355(.A (n_1), .B (n_7), .Y (s[2]));
  ADDFX1 g356(.A (b[1]), .B (a[1]), .CI (n_4), .CO (n_7), .S (s[1]));
  ADDFX1 g357(.A (b[0]), .B (a[0]), .CI (ci), .CO (n_4), .S (s[0]));
  CLKINVX1 g358(.A (n_2), .Y (n_3));
  CLKXOR2X1 g359(.A (b[3]), .B (a[3]), .Y (n_2));
  CLKXOR2X1 g360(.A (b[2]), .B (a[2]), .Y (n_1));
  NAND2XL g361(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module four_lac_3(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire n_0, n_1, n_2, n_3, n_4, n_7, n_9;
  OAI21XL g352(.A0 (n_9), .A1 (n_3), .B0 (n_0), .Y (c1));
  MXI2XL g353(.A (n_2), .B (n_3), .S0 (n_9), .Y (s[3]));
  AOI22XL g354(.A0 (n_7), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_9));
  CLKXOR2X1 g355(.A (n_1), .B (n_7), .Y (s[2]));
  ADDFX1 g356(.A (b[1]), .B (a[1]), .CI (n_4), .CO (n_7), .S (s[1]));
  ADDFX1 g357(.A (b[0]), .B (a[0]), .CI (ci), .CO (n_4), .S (s[0]));
  CLKINVX1 g358(.A (n_2), .Y (n_3));
  CLKXOR2X1 g359(.A (b[3]), .B (a[3]), .Y (n_2));
  CLKXOR2X1 g360(.A (b[2]), .B (a[2]), .Y (n_1));
  NAND2XL g361(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

module sixteen_lac(a, b, ci, s, c1);
  input [15:0] a, b;
  input ci;
  output [15:0] s;
  output c1;
  wire [15:0] a, b;
  wire ci;
  wire [15:0] s;
  wire c1;
  wire [2:0] c;
  four_lac g1(a[3:0], b[3:0], ci, s[3:0], c[0]);
  four_lac_1 g2(a[7:4], b[7:4], c[0], s[7:4], c[1]);
  four_lac_2 g3(a[11:8], b[11:8], c[1], s[11:8], c[2]);
  four_lac_3 g4(a[15:12], b[15:12], c[2], s[15:12], c1);
endmodule

