
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Oct 22 2019 15:57:31 IST (Oct 22 2019 10:27:31 UTC)

// Verification Directory fv/shift 

module bit_adder(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (a), .CI (b), .CO (c1), .S (s));
endmodule

module shift(s, a, b, clk, rst, c);
  input [3:0] a, b;
  input clk, rst;
  output [3:0] s;
  output c;
  wire [3:0] a, b;
  wire clk, rst;
  wire [3:0] s;
  wire c;
  wire [3:0] t1;
  wire [3:0] t2;
  wire [1:0] p;
  wire [3:0] t3;
  wire [2:0] i;
  wire car, n_0, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  bit_adder g1(t1[0], t2[0], car, p[0], p[1]);
  CLKINVX2 g231(.A (rst), .Y (n_22));
  SDFFQX1 \s_reg[0] (.CK (clk), .D (s[0]), .SI (t3[0]), .SE (n_21), .Q
       (s[0]));
  SDFFQX1 c_reg(.CK (clk), .D (c), .SI (car), .SE (n_21), .Q (c));
  SDFFRHQX1 \i_reg[2] (.RN (n_22), .CK (clk), .D (n_2), .SI (i[2]), .SE
       (n_3), .Q (i[2]));
  SDFFQX1 \s_reg[1] (.CK (clk), .D (s[1]), .SI (t3[1]), .SE (n_21), .Q
       (s[1]));
  SDFFQX1 \s_reg[2] (.CK (clk), .D (s[2]), .SI (t3[2]), .SE (n_21), .Q
       (s[2]));
  SDFFQX1 \s_reg[3] (.CK (clk), .D (s[3]), .SI (t3[3]), .SE (n_21), .Q
       (s[3]));
  DFFSRHQX1 \t1_reg[0] (.RN (n_8), .SN (n_17), .CK (clk), .D (t1[1]),
       .Q (t1[0]));
  DFFSRHQX1 \t2_reg[0] (.RN (n_11), .SN (n_16), .CK (clk), .D (t2[1]),
       .Q (t2[0]));
  DFFSRHQX1 \t2_reg[1] (.RN (n_9), .SN (n_10), .CK (clk), .D (t2[2]),
       .Q (t2[1]));
  DFFSRHQX1 \t1_reg[1] (.RN (n_14), .SN (n_12), .CK (clk), .D (t1[2]),
       .Q (t1[1]));
  DFFRHQX1 \t3_reg[0] (.RN (n_22), .CK (clk), .D (t3[1]), .Q (t3[0]));
  SDFFRHQX1 \i_reg[1] (.RN (n_22), .CK (clk), .D (i[0]), .SI (n_0), .SE
       (i[1]), .Q (i[1]));
  DFFSRHQX1 \t1_reg[2] (.RN (n_6), .SN (n_19), .CK (clk), .D (t1[3]),
       .Q (t1[2]));
  DFFSRHQX1 \t2_reg[2] (.RN (n_4), .SN (n_15), .CK (clk), .D (t2[3]),
       .Q (t2[2]));
  DFFRHQX1 \t3_reg[1] (.RN (n_22), .CK (clk), .D (t3[2]), .Q (t3[1]));
  AND2X4 g501(.A (n_20), .B (n_22), .Y (n_21));
  DFFSRHQX1 \t1_reg[3] (.RN (n_13), .SN (n_5), .CK (clk), .D (t1[0]),
       .Q (t1[3]));
  DFFSRHQX1 \t2_reg[3] (.RN (n_7), .SN (n_18), .CK (clk), .D (t2[0]),
       .Q (t2[3]));
  NOR3X1 g504(.A (i[1]), .B (i[0]), .C (n_2), .Y (n_20));
  DFFRHQX1 \t3_reg[2] (.RN (n_22), .CK (clk), .D (t3[3]), .Q (t3[2]));
  NAND2XL g506(.A (a[2]), .B (rst), .Y (n_19));
  NAND2XL g507(.A (b[3]), .B (rst), .Y (n_18));
  NAND2XL g508(.A (a[0]), .B (rst), .Y (n_17));
  NAND2XL g509(.A (b[0]), .B (rst), .Y (n_16));
  NAND2XL g510(.A (b[2]), .B (rst), .Y (n_15));
  OR2X1 g511(.A (a[1]), .B (n_22), .Y (n_14));
  OR2X1 g512(.A (a[3]), .B (n_22), .Y (n_13));
  DFFRHQX1 car_reg(.RN (n_22), .CK (clk), .D (p[1]), .Q (car));
  DFFRHQX1 \t3_reg[3] (.RN (n_22), .CK (clk), .D (p[0]), .Q (t3[3]));
  NAND2XL g516(.A (a[1]), .B (rst), .Y (n_12));
  OR2X1 g517(.A (b[0]), .B (n_22), .Y (n_11));
  NAND2XL g518(.A (b[1]), .B (rst), .Y (n_10));
  OR2X1 g519(.A (b[1]), .B (n_22), .Y (n_9));
  OR2X1 g520(.A (a[0]), .B (n_22), .Y (n_8));
  OR2X1 g521(.A (b[3]), .B (n_22), .Y (n_7));
  OR2X1 g522(.A (a[2]), .B (n_22), .Y (n_6));
  NAND2XL g523(.A (a[3]), .B (rst), .Y (n_5));
  OR2X1 g524(.A (b[2]), .B (n_22), .Y (n_4));
  NAND2XL g525(.A (i[1]), .B (i[0]), .Y (n_3));
  CLKINVX1 g526(.A (i[2]), .Y (n_2));
  DFFRX1 \i_reg[0] (.RN (n_22), .CK (clk), .D (n_0), .Q (i[0]), .QN
       (n_0));
endmodule

