
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 11 2019 12:07:19 IST (Nov 11 2019 06:37:19 UTC)

// Verification Directory fv/fsm 

module fsm(clk, rst, x, y);
  input clk, rst, x;
  output y;
  wire clk, rst, x;
  wire y;
  wire [3:0] state;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_37;
  wire n_38;
  OAI21XL g2241(.A0 (n_22), .A1 (n_0), .B0 (n_29), .Y (n_32));
  OAI211X1 g2247(.A0 (n_25), .A1 (n_8), .B0 (n_26), .C0 (n_13), .Y
       (n_31));
  OAI211X1 g2245(.A0 (n_27), .A1 (n_9), .B0 (n_28), .C0 (n_10), .Y
       (n_30));
  AOI33XL g2246(.A0 (state[3]), .A1 (n_21), .A2 (n_23), .B0 (n_14), .B1
       (n_4), .B2 (n_7), .Y (n_29));
  AOI22X1 g2250(.A0 (x), .A1 (n_12), .B0 (n_27), .B1 (state[2]), .Y
       (n_28));
  AOI21XL g2251(.A0 (n_25), .A1 (state[0]), .B0 (n_18), .Y (n_26));
  OAI21XL g2248(.A0 (n_23), .A1 (n_27), .B0 (n_5), .Y (n_24));
  AOI21X1 g2253(.A0 (n_20), .A1 (n_17), .B0 (n_19), .Y (n_22));
  OAI32X1 g2254(.A0 (n_38), .A1 (state[1]), .A2 (n_15), .B0 (n_20), .B1
       (n_6), .Y (n_21));
  SDFFRHQX1 n_reg(.RN (rst), .CK (clk), .D (x), .SI (n_37), .SE (n_19),
       .Q (n_37));
  NOR2XL g2258(.A (x), .B (n_17), .Y (n_18));
  OAI21X1 g2249(.A0 (n_25), .A1 (n_15), .B0 (n_3), .Y (n_16));
  NAND2XL g2255(.A (n_14), .B (n_13), .Y (n_27));
  CLKINVX1 g2259(.A (n_12), .Y (n_17));
  ADDHX1 g2257(.A (x), .B (n_2), .CO (n_14), .S (n_20));
  NAND2BX1 g2256(.AN (n_38), .B (n_10), .Y (n_25));
  NOR2XL g2260(.A (n_9), .B (n_8), .Y (n_12));
  NAND2XL g2261(.A (n_10), .B (n_13), .Y (n_19));
  INVXL g2265(.A (n_6), .Y (n_7));
  NAND2XL g2269(.A (state[1]), .B (n_15), .Y (n_6));
  NAND2XL g2268(.A (n_23), .B (n_5), .Y (n_9));
  NOR2XL g2266(.A (state[3]), .B (n_23), .Y (n_4));
  NAND2XL g2262(.A (n_15), .B (n_3), .Y (n_8));
  NAND2XL g2264(.A (state[2]), .B (state[3]), .Y (n_10));
  NAND2XL g2263(.A (state[0]), .B (state[1]), .Y (n_13));
  CLKINVX1 g2273(.A (n_37), .Y (n_2));
  DFFRX1 \state_reg[2] (.RN (rst), .CK (clk), .D (n_30), .Q (state[2]),
       .QN (n_23));
  DFFRX1 \state_reg[0] (.RN (rst), .CK (clk), .D (n_31), .Q (state[0]),
       .QN (n_15));
  DFFRX1 y_reg(.RN (rst), .CK (clk), .D (n_32), .Q (y), .QN (n_0));
  DFFRX1 \state_reg[1] (.RN (rst), .CK (clk), .D (n_16), .Q (state[1]),
       .QN (n_3));
  DFFRX1 \state_reg[3] (.RN (rst), .CK (clk), .D (n_24), .Q (state[3]),
       .QN (n_5));
  NAND2BX1 g2(.AN (x), .B (n_37), .Y (n_38));
endmodule

