
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 20:53:15 IST (Sep  4 2019 15:23:15 UTC)

// Verification Directory fv/q1_c 

module q1_c(a, b, c, d, e, o_p);
  input a, b, c, d, e;
  output o_p;
  wire a, b, c, d, e;
  wire o_p;
  wire n_0, n_1;
  OAI22XL g33(.A0 (n_1), .A1 (e), .B0 (n_0), .B1 (a), .Y (o_p));
  AND2X1 g34(.A (d), .B (c), .Y (n_1));
  INVXL g35(.A (b), .Y (n_0));
endmodule

