
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:36:34 IST (Sep 10 2019 07:06:34 UTC)

// Verification Directory fv/two_mux 

module two_mux(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

