
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 14 2019 11:45:04 IST (Sep 14 2019 06:15:04 UTC)

// Verification Directory fv/encoder 

module encoder(a0, a1, a2, a3, a4, a5, a6, a7, s0, s1, s2, v, en);
  input a0, a1, a2, a3, a4, a5, a6, a7, en;
  output s0, s1, s2, v;
  wire a0, a1, a2, a3, a4, a5, a6, a7, en;
  wire s0, s1, s2, v;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  OA21XL g250(.A0 (a7), .A1 (n_12), .B0 (en), .Y (s0));
  AOI2BB1XL g252(.A0N (a5), .A1N (n_7), .B0 (a6), .Y (n_12));
  NAND2BXL g251(.AN (s2), .B (n_8), .Y (v));
  NAND2XL g253(.A (n_3), .B (n_6), .Y (s1));
  OAI31XL g254(.A0 (a1), .A1 (a0), .A2 (n_5), .B0 (en), .Y (n_8));
  NOR2XL g255(.A (a4), .B (n_2), .Y (n_7));
  NAND3XL g256(.A (en), .B (n_4), .C (n_5), .Y (n_6));
  OAI21XL g257(.A0 (n_4), .A1 (n_0), .B0 (n_3), .Y (s2));
  AOI21XL g258(.A0 (a1), .A1 (n_1), .B0 (a3), .Y (n_2));
  OAI21XL g259(.A0 (a6), .A1 (a7), .B0 (en), .Y (n_3));
  OR2X1 g260(.A (a3), .B (a2), .Y (n_5));
  NOR2XL g261(.A (a5), .B (a4), .Y (n_4));
  INVXL g262(.A (a2), .Y (n_1));
  INVXL g263(.A (en), .Y (n_0));
endmodule

