
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 04:15:45 IST (Sep  4 2019 22:45:45 UTC)

// Verification Directory fv/NOT 

module NOT(a, b);
  input a;
  output b;
  wire a;
  wire b;
  INVXL g2(.A (a), .Y (b));
endmodule


