
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 26 2019 15:28:41 IST (Sep 26 2019 09:58:41 UTC)

// Verification Directory fv/four 

module bit_adder(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (c), .B (b), .CI (a), .CO (c1), .S (s));
endmodule

module bit_adder_1(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (b), .B (a), .CI (c), .CO (c1), .S (s));
endmodule

module bit_adder_2(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (b), .B (a), .CI (c), .CO (c1), .S (s));
endmodule

module bit_adder_3(a, b, c, s, c1);
  input a, b, c;
  output s, c1;
  wire a, b, c;
  wire s, c1;
  ADDFX1 g2(.A (b), .B (a), .CI (c), .CO (c1), .S (s));
endmodule

module four(a, b, ci, s, c1);
  input [3:0] a, b;
  input ci;
  output [3:0] s;
  output c1;
  wire [3:0] a, b;
  wire ci;
  wire [3:0] s;
  wire c1;
  wire [0:2] d;
  bit_adder g1(a[0], b[0], ci, s[0], d[0]);
  bit_adder_1 g2(a[1], b[1], d[0], s[1], d[1]);
  bit_adder_2 g3(a[2], b[2], d[1], s[2], d[2]);
  bit_adder_3 g4(a[3], b[3], d[2], s[3], c1);
endmodule

