
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:35:35 IST (Sep 10 2019 07:05:35 UTC)

// Verification Directory fv/four_mux 

module two_mux(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_1(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_2(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module four_mux(o_p, a, b, c, d, s1, s2);
  input a, b, c, d, s1, s2;
  output o_p;
  wire a, b, c, d, s1, s2;
  wire o_p;
  wire b1, b2;
  two_mux g1(b1, a, b, s1);
  two_mux_1 g2(b2, c, d, s1);
  two_mux_2 g3(o_p, b1, b2, s2);
endmodule

