
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 10 2019 10:50:02 IST (Nov 10 2019 05:20:02 UTC)

// Verification Directory fv/shiftreg 

module shiftreg(data_in, MSB_in, LSB_in, s1, s0, clk, data_out);
  input [3:0] data_in;
  input MSB_in, LSB_in, s1, s0, clk;
  output [3:0] data_out;
  wire [3:0] data_in;
  wire MSB_in, LSB_in, s1, s0, clk;
  wire [3:0] data_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11;
  DFFQX1 \data_out_temp_reg[0] (.CK (clk), .D (n_11), .Q (data_out[0]));
  DFFQX1 \data_out_temp_reg[1] (.CK (clk), .D (n_10), .Q (data_out[1]));
  DFFQX1 \data_out_temp_reg[2] (.CK (clk), .D (n_8), .Q (data_out[2]));
  DFFQX1 \data_out_temp_reg[3] (.CK (clk), .D (n_7), .Q (data_out[3]));
  OAI2BB1XL g290(.A0N (n_9), .A1N (data_out[0]), .B0 (n_1), .Y (n_11));
  OAI2BB1XL g291(.A0N (n_9), .A1N (data_out[1]), .B0 (n_0), .Y (n_10));
  OAI2BB1XL g288(.A0N (n_9), .A1N (data_out[2]), .B0 (n_6), .Y (n_8));
  OAI2BB1XL g289(.A0N (n_9), .A1N (data_out[3]), .B0 (n_5), .Y (n_7));
  AOI222XL g293(.A0 (data_in[2]), .A1 (n_4), .B0 (data_in[1]), .B1
       (n_3), .C0 (n_2), .C1 (data_in[3]), .Y (n_6));
  AOI222XL g294(.A0 (data_in[3]), .A1 (n_4), .B0 (data_in[2]), .B1
       (n_3), .C0 (n_2), .C1 (MSB_in), .Y (n_5));
  AOI222XL g292(.A0 (data_in[0]), .A1 (n_4), .B0 (LSB_in), .B1 (n_3),
       .C0 (n_2), .C1 (data_in[1]), .Y (n_1));
  AOI222XL g295(.A0 (data_in[1]), .A1 (n_4), .B0 (data_in[2]), .B1
       (n_2), .C0 (n_3), .C1 (data_in[0]), .Y (n_0));
  NOR2BXL g298(.AN (s0), .B (s1), .Y (n_2));
  AND2X1 g296(.A (s0), .B (s1), .Y (n_9));
  NOR2XL g297(.A (s0), .B (s1), .Y (n_4));
  NOR2BXL g299(.AN (s1), .B (s0), .Y (n_3));
endmodule

