
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 04:21:08 IST (Sep  4 2019 22:51:08 UTC)

// Verification Directory fv/OR 

module OR(a, b, c);
  input a, b;
  output c;
  wire a, b;
  wire c;
  OR2X1 g2(.A (b), .B (a), .Y (c));
endmodule


