
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov  1 2019 16:52:13 IST (Nov  1 2019 11:22:13 UTC)

// Verification Directory fv/radix4fft 

module radix4fft(i0, i1, i2, i3, e, ei, f, fi, g, gi, h, hi);
  input [1:0] i0, i1, i2, i3;
  output [3:0] e, ei, f, fi, g, gi, h, hi;
  wire [1:0] i0, i1, i2, i3;
  wire [3:0] e, ei, f, fi, g, gi, h, hi;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_40, n_41, n_42, n_43, n_45, n_46, n_47;
  wire n_49, n_69;
  assign hi[0] = fi[0];
  assign hi[2] = hi[3];
  assign h[0] = f[0];
  assign h[1] = f[1];
  assign h[2] = f[3];
  assign h[3] = f[3];
  assign gi[0] = 1'b0;
  assign gi[1] = 1'b0;
  assign gi[2] = 1'b0;
  assign gi[3] = 1'b0;
  assign g[0] = e[0];
  assign fi[2] = fi[3];
  assign f[2] = f[3];
  assign ei[0] = 1'b0;
  assign ei[1] = 1'b0;
  assign ei[2] = 1'b0;
  assign ei[3] = 1'b0;
  OAI21XL g1236(.A0 (n_45), .A1 (n_46), .B0 (n_47), .Y (e[2]));
  INVXL g1234(.A (n_49), .Y (g[2]));
  ADDFX1 g1235(.A (n_24), .B (n_2), .CI (n_36), .CO (g[3]), .S (n_49));
  NAND2XL g1239(.A (n_46), .B (n_45), .Y (n_47));
  OAI21XL g1240(.A0 (n_43), .A1 (n_46), .B0 (n_42), .Y (e[3]));
  NAND2BXL g1241(.AN (n_43), .B (n_42), .Y (n_45));
  NAND2BXL g1242(.AN (n_41), .B (n_40), .Y (n_42));
  NOR2BXL g1243(.AN (n_41), .B (n_40), .Y (n_43));
  INVXL g1237(.A (n_37), .Y (g[1]));
  INVXL g1244(.A (n_35), .Y (e[1]));
  ADDFX1 g1238(.A (n_27), .B (n_33), .CI (n_32), .CO (n_36), .S (n_37));
  ADDFX1 g1245(.A (n_25), .B (n_10), .CI (n_34), .CO (n_40), .S (n_35));
  MXI2XL g1255(.A (n_31), .B (n_30), .S0 (n_33), .Y (n_34));
  MXI2XL g1256(.A (n_31), .B (n_30), .S0 (n_12), .Y (n_32));
  MXI2XL g1253(.A (n_30), .B (n_31), .S0 (n_26), .Y (fi[1]));
  MXI2XL g1254(.A (n_31), .B (n_30), .S0 (n_23), .Y (hi[1]));
  OAI222XL g1249(.A0 (i2[1]), .A1 (n_18), .B0 (i1[1]), .B1 (i0[1]), .C0
       (n_17), .C1 (i3[1]), .Y (n_41));
  AOI222XL g1246(.A0 (i0[0]), .A1 (n_26), .B0 (n_3), .B1 (n_14), .C0
       (n_4), .C1 (i2[0]), .Y (n_27));
  AOI22XL g1247(.A0 (fi[0]), .A1 (n_69), .B0 (i0[0]), .B1 (i2[0]), .Y
       (n_25));
  MXI2XL g1250(.A (n_11), .B (fi[0]), .S0 (f[0]), .Y (e[0]));
  OAI21XL g1258(.A0 (i1[1]), .A1 (i3[1]), .B0 (n_13), .Y (n_24));
  INVXL g1261(.A (n_31), .Y (n_30));
  OAI21XL g1259(.A0 (n_23), .A1 (n_9), .B0 (n_20), .Y (hi[3]));
  OAI21XL g1248(.A0 (n_22), .A1 (n_16), .B0 (n_15), .Y (f[3]));
  OAI2BB1XL g1260(.A0N (n_20), .A1N (n_26), .B0 (n_19), .Y (fi[3]));
  NAND2XL g1265(.A (n_20), .B (n_19), .Y (n_31));
  OA21X1 g1267(.A0 (i0[1]), .A1 (n_0), .B0 (n_20), .Y (n_18));
  AOI21XL g1268(.A0 (i2[1]), .A1 (n_5), .B0 (n_16), .Y (n_17));
  NAND2BXL g1266(.AN (n_16), .B (n_15), .Y (n_33));
  OAI21XL g1252(.A0 (i0[0]), .A1 (i1[0]), .B0 (n_22), .Y (n_14));
  AO21X1 g1269(.A0 (i3[1]), .A1 (i1[1]), .B0 (n_12), .Y (n_13));
  OAI21XL g1270(.A0 (n_7), .A1 (i2[0]), .B0 (n_22), .Y (f[0]));
  INVXL g1257(.A (n_11), .Y (fi[0]));
  OAI21XL g1264(.A0 (i1[0]), .A1 (i3[0]), .B0 (n_10), .Y (n_11));
  INVXL g1277(.A (n_9), .Y (n_19));
  NAND2XL g1272(.A (i0[1]), .B (n_6), .Y (n_15));
  NOR2XL g1278(.A (i0[1]), .B (n_6), .Y (n_16));
  NAND2XL g1276(.A (i2[0]), .B (n_7), .Y (n_22));
  NAND2XL g1282(.A (i3[1]), .B (n_5), .Y (n_20));
  OAI2BB1XL g1263(.A0N (i3[0]), .A1N (i0[0]), .B0 (i1[0]), .Y (n_4));
  NOR2XL g1281(.A (i3[0]), .B (n_7), .Y (n_12));
  NOR2XL g1279(.A (i3[1]), .B (n_5), .Y (n_9));
  NAND2XL g1280(.A (i1[0]), .B (n_3), .Y (n_23));
  NOR2XL g1283(.A (i1[0]), .B (n_3), .Y (n_26));
  NOR2XL g1273(.A (i3[1]), .B (i2[1]), .Y (n_46));
  AND2X1 g1275(.A (i2[1]), .B (i0[1]), .Y (n_2));
  NAND2XL g1274(.A (i3[0]), .B (i1[0]), .Y (n_10));
  INVXL g1284(.A (i2[1]), .Y (n_6));
  INVXL g1287(.A (i0[0]), .Y (n_7));
  INVXL g1285(.A (i3[1]), .Y (n_0));
  INVXL g1289(.A (i1[1]), .Y (n_5));
  INVXL g1286(.A (i3[0]), .Y (n_3));
  XNOR2XL g2(.A (n_33), .B (n_22), .Y (f[1]));
  NAND2BX1 g1290(.AN (i2[0]), .B (n_7), .Y (n_69));
endmodule

