
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 03:15:37 IST (Sep  4 2019 21:45:37 UTC)

// Verification Directory fv/AND 

module AND(a, b, c);
  input a, b;
  output c;
  wire a, b;
  wire c;
  AND2XL g8(.A (b), .B (a), .Y (c));
endmodule

