
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:41:23 IST (Sep 10 2019 07:11:23 UTC)

// Verification Directory fv/two_de 

module two_de(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

