
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:39:19 IST (Sep 10 2019 07:09:19 UTC)

// Verification Directory fv/four_de 

module two_de_1(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de_2(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2XL g18(.A (s), .B (i_p), .Y (b));
endmodule

module two_de(i_p, a, b, s);
  input i_p, s;
  output a, b;
  wire i_p, s;
  wire a, b;
  NOR2BXL g17(.AN (i_p), .B (s), .Y (a));
  AND2X1 g18(.A (s), .B (i_p), .Y (b));
endmodule

module four_de(i_p, a, b, c, d, s1, s2);
  input i_p, s1, s2;
  output a, b, c, d;
  wire i_p, s1, s2;
  wire a, b, c, d;
  wire a1, a2;
  two_de_1 g1(a1, a, b, s1);
  two_de_2 g2(a2, c, d, s1);
  two_de gg(i_p, a1, a2, s2);
endmodule

