
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 04:02:21 IST (Sep  4 2019 22:32:21 UTC)

// Verification Directory fv/NAND 

module NAND(a, b, c);
  input a, b;
  output c;
  wire a, b;
  wire c;
  NAND2XL g4(.A (b), .B (a), .Y (c));
endmodule

