
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 10 2019 12:18:23 IST (Sep 10 2019 06:48:23 UTC)

// Verification Directory fv/eight_mux 

module two_mux(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_1(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_2(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module four_mux(o_p, a, b, c, d, s1, s2);
  input a, b, c, d, s1, s2;
  output o_p;
  wire a, b, c, d, s1, s2;
  wire o_p;
  wire b1, b2;
  two_mux g1(b1, a, b, s1);
  two_mux_1 g2(b2, c, d, s1);
  two_mux_2 g3(o_p, b1, b2, s2);
endmodule

module two_mux_3(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_4(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module two_mux_5(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module four_mux_1(o_p, a, b, c, d, s1, s2);
  input a, b, c, d, s1, s2;
  output o_p;
  wire a, b, c, d, s1, s2;
  wire o_p;
  wire b1, b2;
  two_mux_3 g1(.o_p (b1), .a (a), .b (b), .s (s1));
  two_mux_4 g2(.o_p (b2), .a (c), .b (d), .s (s1));
  two_mux_5 g3(.o_p (o_p), .a (b1), .b (b2), .s (s2));
endmodule

module two_mux_6(o_p, a, b, s);
  input a, b, s;
  output o_p;
  wire a, b, s;
  wire o_p;
  MX2X1 g24(.A (a), .B (b), .S0 (s), .Y (o_p));
endmodule

module eight_mux(o_p, a1, a2, a3, a4, a5, a6, a7, a8, s1, s2, s3);
  input a1, a2, a3, a4, a5, a6, a7, a8, s1, s2, s3;
  output o_p;
  wire a1, a2, a3, a4, a5, a6, a7, a8, s1, s2, s3;
  wire o_p;
  wire b1, b2;
  four_mux g1(b1, a1, a2, a3, a4, s1, s2);
  four_mux_1 g2(b2, a5, a6, a7, a8, s1, s2);
  two_mux_6 g3(o_p, b1, b2, s3);
endmodule

